// src/pages/About.vue
<template>
  <v-container>
    <v-layout>
      <v-flex xs10>
        <div class=display-1>BGmi:</div>
        <p class=subheading>version: {{ $store.state.bgmiVersion }}</p>
        <p> BGmi HTTP Service 基于
          <a href="https://github.com/BGmi/BGmi" target="_blank">BGmi</a> 构建。<br>
        </p>
        其中，BGmi 的数据来源于
        <a href="https://bangumi.moe" target="_blank">萌番组
          <sup>大好きだよ</sup>
        </a>/
        <a href="https://mikanani.me/" target="_blank">蜜柑计划 - Mikan Project</a>/
        <a href="http://share.dmhy.org/" target="_blank">動漫花園資源網</a>

        <br>
        <br>
        <div class=display-1>BGmi-frontend:</div>
        <p class=subheading>version: {{ version }}</p>

        <h3>致谢</h3>
        <ul>
          <li>
            <a href="https://bangumi.moe" target="_blank">萌番组</a><br>
          </li>
          <li>
            <a href="https://mikanani.me/" target="_blank">蜜柑计划</a>
          </li>
          <li>
            <a href="https://aria2.github.io" target="_blank">aria2</a>
          </li>
          <li>
            <a href="https://github.com/DIYgod/DPlayer" target="_blank">DPlayer</a>
          </li>
        </ul>
        <!-- <hr> -->
        <br>
        <h3>BGmi Creator:
          <a href="https://github.com/RicterZ" target="_blank">github/RicterZ </a>
        </h3>
        <h3>Contributors:
          <a href="https://github.com/BGmi/BGmi/graphs/contributors">github/BGmi/BGmi/contributors</a>
        </h3>
        <!-- <hr> -->
        <br>
        <h3>Bug Report</h3>
        <ul>
          <li>
            <a href="https://github.com/BGmi/BGmi/issues">BGmi Bug Report</a>
          </li>
          <li>
            <a href="https://github.com/BGmi/BGmi-frontend/issues">BGmi-frontend Bug Report</a>
          </li>
        </ul>
      </v-flex>
    </v-layout>
  </v-container>
</template>
<script>
export default {
  name: 'About',
  data () {
    return {
      version: process.env.VERSION
    }
  }
}
</script>
<style>
</style>

// src/pages/about/index.tsx
import { Box, Fade, Heading, Highlight, Link, ListItem, Stack, Text, UnorderedList } from '@chakra-ui/react';

import { useBangumi } from '~/hooks/use-bangumi';
import { useColorMode } from '~/hooks/use-color-mode';

export default function About() {
  const { data } = useBangumi();
  const { colorMode } = useColorMode();
  const highlightStyles = { px: '1', bg: 'gray.100', color: 'gray.900', rounded: '4px' };
  return (
    <Box maxW="4xl">
      <Heading>
        BGmi{' '}
        <Fade style={{ display: 'inline' }} in={!!data?.version}>
          {data?.version}
        </Fade>
      </Heading>
      <Text mt="2">一个用来追番的命令行程序</Text>
      <Text>
        HTTP Service 基于{' '}
        <Link href="https://github.com/BGmi/BGmi" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
          BGmi
        </Link>{' '}
        构建
      </Text>

      <Stack mt="8" spacing="8">
        <Box>
          <Heading size="md" mb="3">
            有什么特性？
          </Heading>
          <UnorderedList spacing="2">
            <ListItem>
              <Highlight query={['Bangumi_Moe', 'Mikan_Project', '大马哈鱼']} styles={highlightStyles}>
                多个数据源可选 Bangumi_Moe Mikan_Project 或者 大马哈鱼
              </Highlight>
            </ListItem>
            <ListItem>
              <Highlight query={['Aria2', 'Transmission', 'qBittorrent', 'Deluge']} styles={highlightStyles}>
                使用 Aria2 Transmission qBittorrent 或者 Deluge 来下载你的番剧
              </Highlight>
            </ListItem>
            <ListItem>
              <Highlight query={['RSS Feed', 'ICS']} styles={highlightStyles}>
                提供 RSS Feed 和移动设备支持的 ICS 格式日历
              </Highlight>
            </ListItem>
            <ListItem>下载番剧时的过滤器 支持关键词, 字幕组和正则</ListItem>
            <ListItem>番剧放送列表和剧集信息</ListItem>
          </UnorderedList>
        </Box>

        <Box>
          <Heading size="md">BGmi Frontend {import.meta.env.VITE_APP_VERSION}</Heading>
          <Text mt="2">
            <Highlight query={['Vite', 'Chakra UI']} styles={highlightStyles}>
              基于 Vite 和 Chakra UI 构建
            </Highlight>
          </Text>
          <Text mt="2">支持视频历史观看时长记录</Text>
        </Box>

        <Box>
          <Heading size="md" mb="3">
            致谢
          </Heading>
          <UnorderedList spacing="2">
            <ListItem>
              <Link href="https://bangumi.moe/" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
                萌番组
              </Link>
            </ListItem>
            <ListItem>
              <Link href="https://mikanani.me/" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
                蜜柑计划
              </Link>
            </ListItem>
            <ListItem>
              <Link href="https://aria2.github.io/" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
                Aria2
              </Link>
            </ListItem>
            <ListItem>
              <Link href="https://github.com/DIYgod/DPlayer" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
                DPlayer
              </Link>
            </ListItem>
          </UnorderedList>
        </Box>

        <Box>
          <Text mt="2" fontSize="lg" fontWeight="medium">
            BGmi Creator -{' '}
            <Link href="https://github.com/RicterZ" color="red.300">
              RicterZ
            </Link>
          </Text>
          <Text fontSize="lg" fontWeight="medium">
            BGmi Contributors -{' '}
            <Link href="https://github.com/BGmi/BGmi/graphs/contributors" color="red.300">
              Contributors
            </Link>
          </Text>
        </Box>

        <Box>
          <Heading size="md">Bug Report</Heading>
          <UnorderedList mt="2" spacing="2">
            <ListItem>
              <Link href="https://github.com/BGmi/BGmi/issues" color={colorMode === 'dark' ? 'red.100' : 'red.400'}>
                BGmi Bug Report
              </Link>
            </ListItem>
            <ListItem>
              <Link
                href="https://github.com/BGmi/BGmi-frontend/issues"
                color={colorMode === 'dark' ? 'red.100' : 'red.400'}
              >
                BGmi-frontend Bug Report
              </Link>
            </ListItem>
          </UnorderedList>
        </Box>
      </Stack>
    </Box>
  );
}
