// src/pages/resource/index.tsx
import { Box, Stack } from '@chakra-ui/react';

import Link from '~/components/router-link';

export default function Resource() {
  return (
    <Box>
      <Stack spacing="2">
        <Link href="/resource/feed.xml" target="_blank" color="blue.200">Rss Feed</Link>
        <Link href="/resource/calendar.ics" target="_blank" color="blue.200">ICS Calendar for mobile phone</Link>
      </Stack>
    </Box>
  );
}

// src/components/Resource/index.vue
<template>
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-content">
              <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                  <div class="tim-typo">
                    <a href="/resource/feed.xml">
                      <md-button>
                        <h5>Rss Feed</h5>
                      </md-button>
                    </a>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                  <div class="tim-typo">
                    <a href="/resource/calendar.ics">
                      <md-button>
                        <h5>ICS Calendar for mobile phone</h5>
                      </md-button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'resource',
    components: {},
    created () { },
    data () {
      return {}
    },
    methods: {}
  }
</script>

<style lang="scss" scoped>

</style>
