// pages/resource/index.tsx
import { Box, Link, Stack } from '@chakra-ui/react';

export default function Resource() {
  // 与原来保持一致
  return (
    <Box>
      <Stack spacing="2">
        <Link href="/resource/feed.xml" target="_blank" color="blue.200">Rss Feed</Link>
        <Link href="/resource/calendar.ics" target="_blank" color="blue.200">ICS Calendar for mobile phone</Link>
      </Stack>
    </Box>
  );
}

// src/pages/Resource.vue
<template>
  <v-container>
    <v-layout
      row
      wrap
    >
      <v-flex xs12>
        <a
          href="/resource/feed.xml"
          target="_blank"
        > Rss Feed </a>
      </v-flex>
      <v-flex xs12>
        <a
          href="/resource/calendar.ics"
          target="_blank"
        >
          ICS Calendar for mobile phone
        </a>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script lang="ts">
export default {
  name: 'Resource',
  data() {
    return {};
  },
};
</script>

<style scoped></style>
